language: php
php:
  - '8.0'
  - '8.1'

install:
  - composer install

script:
  - php -d xdebug.mode=coverage vendor/bin/phpunit --coverage-clover=build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls