#!/usr/bin/env php
<?php

echo "\nTag and submit a new production API release.\n\n";

$currentVersion = file_get_contents('VERSION');
echo "\nCurrent version: {$currentVersion}\n";

$input = fopen("php://stdin", "r");

if( isset($argv[1]) ) {
    $version = $argv[1];
	echo "New version: {$version}\n\n";

} else {
	echo "New version: ";
	$version = trim(fgets($input));
	echo "\n";
}

if( empty($version) ){
    echo "ERROR: Invalid version number.\n\n";
    exit;
}

if( version_compare($version, $currentVersion) < 1 ){
	echo "ERROR: Version numbers must advance.\n\n";
	exit;
}

echo "Are you sure you want to do this?  Type 'yes' to continue: ";
if( strtolower(trim(fgets($input))) !== 'yes' ){
	echo "Aborting release.\n\n";
	exit;
}

// Write version number to disk
file_put_contents('VERSION', $version);

// Tag commit and push up tags.
exec("git commit VERSION -m \"Tagging version {$version}\"");
exec("git push");
exec("git tag {$version}");
exec("git push --tags");